[build]
  base = "/data/data/com.termux/files/home/htdocs/"
  command = "npm run build"
  publish = "/data/data/com.termux/files/home/htdocs/lib"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
